### ISSUE TITLE
Design an app icon 

### ISSUE THREAD

**Issue by AbhilashG97** [AbhilashG97/Melonicious#1]
**Summary:** 

The app currently doesn't have an icon. It shows the default Android bot logo. Please create a catchy icon for the app. Also, while creating the icon, please make sure that it is not taken from any third party service.

**Steps to reproduce the issue:** 

1. Build the app
2. Install the app
3. Open the application drawer in your phone

**Expected behaviour:** 

The app should have its own icon.

**Observed behaviour:** 

The default Android-bot icon is displayed in the application drawer. 

**Screenshots/GIFs:** 

![design-logo](https://user-images.githubusercontent.com/20839661/49559497-02c75180-f935-11e8-8ca5-6b0b188686f8.gif)

**Comment by rob729** [comment]
![](https://cdn.iconscout.com/icon/premium/png-256-thumb/git-commit-4-648432.png)
@AbhilashG97 what do you think about this logo?

**Comment by pawank0411** [comment]
can we add App name to the logo?
@AbhilashG97

**Comment by AbhilashG001** [comment]
Hello @rob729, 

The logo looks fine, but I was thinking of maybe having something related to the following in the logo - 

1. An :octocat:  with horns eating a :watermelon:.
1. A :watermelon: with horns with a Git logo on it.  

The app name comes from the word **malicious** as the user is going to keep track of a set of users (which kind of sounds evil and malicious :sweat_smile: ). And I combined the word malicious with Watermelon and that ended up with the name Melonicious. To be honest, someone else came up with this awesome app name.

So, if you would like to work on this issue, can you please try creating something out of the ideas mentioned above. 

I apologize for the delay in my reply. I was travelling hence, I couldn't reply early.

**Comment by AbhilashG001** [comment]
> can we add App name to the logo?
> @AbhilashG97

Hello @Pawan0411, 

If possible, maybe just a logo without the app name would be fine, since the app name would be displayed below the logo in most of the launchers.

I apologize for the delay in my reply. I was travelling hence, I couldn't reply early.

**Comment by jasnasuresh** [comment]
Hello, Can I work on this issue?

**Comment by amrit-choudhary** [comment]
How about this:
![melonlicious logo](https://user-images.githubusercontent.com/6888341/50542133-b55c9e00-0bdb-11e9-9bf7-1a657eb76499.png)

BG: git hub logo
FG: devil + melon

**Comment by amrit-choudhary** [comment]
Revision: added the github logo tail

![melonlicious logo](https://user-images.githubusercontent.com/6888341/50542159-5ea39400-0bdc-11e9-89f7-a3e64a5ba7a5.png)

**Comment by amrit-choudhary** [comment]
Revision 2: color change
![melonlicious logo](https://user-images.githubusercontent.com/6888341/50542197-9959fc00-0bdd-11e9-9915-bdcf1d6a2cde.png)

**Comment by amrit-choudhary** [comment]
![melonlicious logo 64](https://user-images.githubusercontent.com/6888341/50542215-2309c980-0bde-11e9-8ed5-7a2085dbd6e1.png)
![melonlicious logo 128](https://user-images.githubusercontent.com/6888341/50542218-28671400-0bde-11e9-9e45-64359c922e1b.png)
![melonlicious logo 256](https://user-images.githubusercontent.com/6888341/50542219-29984100-0bde-11e9-8f8e-38d35bc5adf9.png)

**Comment by kariekirkpatrick** [comment]
Hi @AbhilashG97, it looks like this issue is still open. I'm a beginner and I'd love to work on this if you're interested. I read the contributor guidelines and what you're looking for in the app logo. Can I work on this? Anything else I should know?
Thanks for your help!

**Comment by AbhilashG001** [comment]
Hello @kariekirkpatrick,

Yes, you may proceed. As of now, nothing much has changed in the project.✨

**Comment by kariekirkpatrick** [comment]
![melonicious-2](https://user-images.githubusercontent.com/38956753/60260820-6b155a80-98a8-11e9-89ba-c151c0107633.png)

![melonicious](https://user-images.githubusercontent.com/38956753/60260852-7ec0c100-98a8-11e9-8035-cbe58763bfa0.png)

**Comment by AbhilashG97** [comment]
Hello @kariekirkpatrick,

The app icons are awesome! ❤️ 
I really liked them, especially the second the icon.

Can you please send a pull request for the app icons? Thank you so much. 🎉
