### ISSUE TITLE
Translations required for the app

### ISSUE THREAD

**Issue by AbhilashG001** [AbhilashG97/Melonicious#11]
**Summary:** 

The app needs to be translated into different languages. Please provide translations for the app. Also, you can only translate the app in the language you are proficient in. Please avoid translating the app into languages that you do not know.

If you are interested to work on this issue, please mention the language that you will be translating the app into over here. 

**Steps to reproduce the issue:** 

1. Open the settings of your phone
1. Change the language of your phone
1. Open the app
1. The language of the app does not change

**Expected behavior:** 

The language of the app should change in accordance with the language set by the user. Please view [this](https://developer.android.com/studio/write/translations-editor) to know how to translate the app.

**Observed behavior:** 

The language of the app does not change when the user changes the language of their phone.

**Device and Android version:** 

Mi A1 [tissot]
Android Oreo (8.1.0)
Stock Android

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue!!

**Comment by AbhilashG001** [comment]
Hi @Starcode71Ooze, that's great! :sparkles: 

I'm assigning this issue to you.

**Comment by gopikaharikumar** [comment]
Hello,Can I work on this issue?
