### ISSUE TITLE
Add About dialog box for the app

### ISSUE THREAD

**Issue by AbhilashG001** [AbhilashG97/Melonicious#2]
**Summary:** 

The app currently does not have an About dialog box which contains the name of the app and its version. 

**Steps to reproduce the issue:** 

1. Open the app
1. The app does not have an about page

**Expected behaviour:** 

The app should have an about page which contains the name of the app, its logo, and version. The mock-up for the same can be found [here](https://github.com/AbhilashG97/Melonicious/blob/master/mockups/Melonicious.pdf). Please view the 9th page of the mock-ups pdf file. 

**Observed behaviour:** 

The app doesn't have an about page. 

**Device and Android version:** 

Mi A1 [tissot]
Android Oreo [8.1.0]
Stock Android

**Screenshots/GIFs:** 
![screenshot_20181215-152946](https://user-images.githubusercontent.com/20839661/50041688-b1c70400-007e-11e9-9b52-504f310a2cf9.png)

**Comment by yashk2000** [comment]
@AbhilashG97 I am working on this issue.

**Comment by AbhilashG001** [comment]
@yashk2000, okay. I'm assigning you this issue. :sparkles:
