### ISSUE TITLE
Migrating to Bottom Navigation Drawer

### ISSUE THREAD

**Issue by AbhilashG001** [AbhilashG97/Melonicious#27]
**Summary:** 

The app currently uses Navigation drawer to switch between fragments, this needs to be replaced with Bottom Navigation Drawer.

**Steps to reproduce the issue:** 

1. Open the app
1. Click on the navigation drawer icon at the top left

**Expected behaviour:** 

The navigation drawer should be replaced with a bottom navigation drawer.

**Observed behaviour:** 

The app has a navigation drawer.

**Device and Android version:** 

Android Virtual Device
Android Pie

**Comment by gouri-panda** [comment]
@AbhilashG97  can  I work on this issue?:)

**Comment by AbhilashG001** [comment]
@gouri-panda, yes, please go ahead. :star2:

**Comment by gouri-panda** [comment]
@AbhilashG97  I saw the menu has 6 items.but the maximum number of items supported by BottomNavigationView is 5.How can we do this?

**Comment by AbhilashG001** [comment]
Hi @gouri-panda,

We don't need the ```About``` and ```Author``` drawer item. They are supposed to be removed and a separate issue has been created for the same. 

You don't have to include ```About``` and ```Author``` drawer item in the bottom navigation drawer. 
If you still have any questions, please do let me know. ✨

**Comment by gouri-panda** [comment]
@AbhilashG97  Please check my PR #32😀

**Comment by AbhilashG001** [comment]
Great job @gouri-panda! 
I'm closing this issue. It has been [resolved](https://github.com/AbhilashG97/Melonicious/pull/32).
