### ISSUE TITLE
Redesign the navigation drawer

### ISSUE THREAD

**Issue by AbhilashG001** [AbhilashG97/Melonicious#3]
**Summary:** 

The navigation drawer of the application does not contain the items and their corresponding icons as depicted in the mockups. Please redesign the navigation drawer as depicted in the mockup. 

**Steps to reproduce the issue:** 

1. Open the app
2. Open the navigation drawer

**Expected behavior:** 

The navigation drawer should look as described in the mock-ups. Please view the 2nd page of the [mock-ups](https://github.com/AbhilashG97/Melonicious/blob/master/mockups/Melonicious.pdf). 

**Observed behavior:** 

The navigation drawer does not look as described in the mockups.

**Device and Android version:** 

Mi A1 [tissot]
Android Oreo (8.1.0)
Stock Android 

**Screenshots/GIFs:** 

![screenshot_20181215-152946](https://user-images.githubusercontent.com/20839661/50048462-f2606500-00f2-11e9-810f-869fe372e4fe.png)

**Comment by abhijitramesh** [comment]
Can I work on this issue?

**Comment by abhijitramesh** [comment]
I am working on this issue @AbhilashG97

**Comment by AbhilashG001** [comment]
@abhijitrameshm, okay. I'm assigning this issue to you. :sparkles:
