### ISSUE TITLE
Add dependencies to the project

### ISSUE THREAD

**Issue by AbhilashG001** [AbhilashG97/Melonicious#4]
**Summary:** 

The following libraries will be used in the project.  Please add the them - 

1. [RxJava](https://github.com/ReactiveX/RxJava)
1. [Material Stepper](https://github.com/stepstone-tech/android-material-stepper)
1. [Picasso](https://github.com/square/picasso)
1. [Dagger 2](https://github.com/google/dagger)

**Steps to reproduce the issue:** 

1. Open the project in Android Studio.
1. Go to the ```app``` :file_folder: and then open [```build.gradle```](https://github.com/AbhilashG97/Melonicious/blob/master/app/build.gradle).

**Expected behaviour:** 

The [```build.gradle(app)```](https://github.com/AbhilashG97/Melonicious/blob/master/app/build.gradle) file should contain the above-mentioned dependencies. 

**Observed behaviour:** 

The build.gradle(app) file does not contain the above-mentioned dependencies.

**Device and Android version:** 

Mi A1 [tissot]
Android Oreo (8.1.0)
Stock Android

**Comment by athiranair2000** [comment]
Hello,can I work on this issue?

**Comment by AbhilashG001** [comment]
Hello @athiranair2000, yes, you can work on this issue. I'm assigning this issue to you. :sparkles:

**Comment by AbhilashG001** [comment]
The issue has been resolved. Thank you. :balloon:
