### ISSUE TITLE
Add double-tap to exit feature 

### ISSUE THREAD

**Issue by AbhilashG001** [AbhilashG97/Melonicious#5]
**Summary:** 

Currently, the app exits on tapping the back button once. Please add a double tap to exit feature wherein the user will be asked to press the back button again when the back button is clicked once.

**Steps to reproduce the issue:** 

1. Open the app
1. Press the back button
1. The app exits on tapping on the back button only once

**Expected behaviour:** 

The app should display a Snackbar asking the user to press the back button again. And when the user taps on the back-button again the app should exit

**Observed behaviour:** 

The app exits on tapping the back-button once.

**Device and Android version:** 

Mi A1 [tissot]
Android Oreo (8.1.0)
Stock Android

**Screenshots/GIFs:** 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20839661/50048996-41f95d80-0100-11e9-917e-a444f24289a9.gif)

**Comment by yashk2000** [comment]
@AbhilashG97 I am working on this issue.

**Comment by AbhilashG001** [comment]
okay @yashk2000, I'm assigning this issue to you. :sparkles:
