### ISSUE TITLE
Change the Floating Action Button icon to a "+" icon 

### ISSUE THREAD

**Issue by AbhilashG001** [AbhilashG97/Melonicious#6]
**Summary:** 

Currently, the app has an incorrect icon for the Floating Action Button. The incorrect icon needs to be changed.

**Steps to reproduce the issue:** 

1. Open the app
1. The icon inside the Floating Action Button is incorrect

**Expected behaviour:** 

There should be a ```+``` icon inside the Floating Action Button.

**Observed behaviour:** 

An incorrect icon is being shown inside the Floating Action Button.

**Device and Android version:** 

Mi A1 [tissot]
Android Oreo (8.1.0)
Stock Android

**Comment by hridyakrishna** [comment]
Hello,can I work on this?

**Comment by AbhilashG001** [comment]
Hi @hsymphonyk, yes please go ahead. I'm assigning this issue to you. :sparkles:

**Comment by hridyakrishna** [comment]
Thank you @AbhilashG97

**Comment by AbhilashG001** [comment]
This issue has been resolved. 😄
