### ISSUE TITLE
Remove hardcoded strings present in the app 

### ISSUE THREAD

**Issue by AbhilashG001** [AbhilashG97/Melonicious#8]
**Summary:** 

Currently, the app has a few hardcoded strings present in the code. This is not good as it affects Internationalization. Please remove the hardcoded strings and reference them from the ```strings.xml``` file.

**Steps to reproduce the issue:** 

Please follow the instructions mentioned in [this](https://stackoverflow.com/questions/25043809/how-can-i-find-all-hard-coded-strings-in-my-project-in-android-studio) StackOverflow post to find hardcoded strings in the project. 

**Expected behaviour:** 

The app should not have any hardcoded strings as it makes it difficult to translate.

**Observed behaviour:** 

The app contains a few hardcoded strings. 

**Device and Android version:** 

Mi A1 [tissot]
Android Oreo (8.1.0)
Stock Android

**Comment by jasnasuresh** [comment]
Hey, Can I work on this issue?

**Comment by AbhilashG001** [comment]
Hi @jasnasuresh, yes, you can work on this issue. I'm assigning this issue to you. :sparkles:
